# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.47
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_version=3.3.1
mod_id=expanded_combat
mod_name=Expanded Combat
mod_license=All Rights Reserved
mod_group_id=com.userofbricks.expanded_combat
mod_authors=Userofbricks
mod_description=An Expansion of Minecraft's combat equipment which includes a reimagining of dinnerbone's quiver.

mixingradle_version=0.7-SNAPSHOT
mixin_version = 0.8.5

cloth_config_api_version = 15.0.140
curios_version=9.0.10+1.21
jei_version=19.21.0.246
