# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_version=3.2.2
modid=expanded_combat
mod_name=Expanded Combat
mod_license=All Rights Reserved
mod_group_id=com.userofbricks.expanded_combat
mod_authors=Userofbricks
mod_description=An Expansion of Minecraft's combat equipment which includes a reimagining of dinnerbone's quiver.

forgegradle_version = 6.0.+
mixingradle_version=0.7-SNAPSHOT
mixin_version = 0.8.5
uses_mixins = true

better_combat_test=false
