# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.daemon=false
org.gradle.debug=false

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.20.6
minecraft_version_range=[1.20.6,1.21)

neo_version=20.6.100-beta
neo_version_range=[20.5,)
loader_version_range=[2,)

mod_version=3.1.2
mod_id=expanded_combat
mod_name=Expanded Combat
mod_license=All Rights Reserved
mod_group_id=com.userofbricks.expanded_combat
mod_authors=Userofbricks
mod_description=An Expansion of Minecraft's combat equipment which includes a reimagining of dinnerbone's quiver.

mixingradle_version=0.7-SNAPSHOT
mixin_version = 0.8.5

cloth_config_api_version = 14.0.126
curios_version=8.0.0-beta+1.20.6
jei_version=17.3.0.52
