package com.userofbricks.testing_ec;

import com.tterrag.registrate.Registrate;
import com.tterrag.registrate.util.nullness.NonNullSupplier;
import com.userofbricks.expanded_combat.ExpandedCombat;
import com.userofbricks.testing_ec.config.PluginConfig;
import com.userofbricks.testing_ec.util.PluginLangStrings;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;


@Mod(TestingPlugin.MODID)
public class TestingPlugin {
    public static final String MODID = ExpandedCombat.MODID + "_test";
    public static final NonNullSupplier<Registrate> REGISTRATE = NonNullSupplier.lazy(() -> Registrate.create(MODID)); //having your registrate reference in a convenient place that loads when the mod first loads is best
    public static PluginConfig CONFIG; //Same as with the Registrate reference keep this in a common location
    public TestingPlugin() {
        PluginLangStrings.registerLang(); //this is for registering all lang that is not generated by a material/a material's items (i.e. Config lang)
        MinecraftForge.EVENT_BUS.register(this);
    }
}